apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: aegis-app
  template:
    metadata:
      labels:
        app: aegis-app
    spec:
      containers:
      - name: aegis-front
        image: {{.Values.image.repository}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80